/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace de.dailab.interprocess.shm {

using System;
using System.Runtime.InteropServices;

public class DataRequest : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DataRequest(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DataRequest obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DataRequest() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ShmDataPINVOKE.delete_DataRequest(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DataRequest() : this(ShmDataPINVOKE.new_DataRequest(), true) {
  }

  public enum Type {
    WAIT_FOR_NEWEST,
    NEWEST_AVAILABLE,
    NEWEST_AVAILABLE_WAIT,
    NEXT_AVAILABLE,
    NEXT_AVAILABLE_WAIT
  }

}

}
