/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace de.dailab.interprocess.shm {

using System;
using System.Runtime.InteropServices;

public class ShmData {
  public static void remove_shm_with_name(string name) {
    ShmDataPINVOKE.remove_shm_with_name(name);
    if (ShmDataPINVOKE.SWIGPendingException.Pending) throw ShmDataPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
